### ISSUE TITLE
Cannot find module '@graphql-tools/delegate' or its corresponding type declarations.

### ISSUE THREAD

**Issue by cernicc** [maticzav/graphql-middleware#314]
Hi. I am getting following error when trying to build my project. I am using the latest middleware version 6.0.0.

```
➜  project git:(master) ✗  npm run build && npm run test

> project@1.0.0 build /home/rok/project
> rm -rf dist && tsc

node_modules/graphql-middleware/dist/types.d.ts:2:31 - error TS2307: Cannot find module '@graphql-tools/delegate' or its corresponding type declarations.

2 import { StitchingInfo } from '@graphql-tools/delegate';
                                ~~~~~~~~~~~~~~~~~~~~~~~~~

Found 1 error.

```

**Comment by maticzav** [comment]
Hey 👋,

Could you share a small reproduction repository so we can better help you with your issue?

**Comment by cernicc** [comment]
I think i figure it out. Graphql-shield is still using an older version. If I use 4.0.0 of the middleware then it works.

Here is the reproduction repo if you want to try it out.
https://github.com/cernicc/temp

**Comment by cernicc** [comment]
Thank you. I am closing this issue.

**Comment by arnaud-zg** [comment]
I also have this issue on my side, I think we have this problem because the module `@graphql-tools/delegate` is not a dependency of `graphql-middleware`. That's why we don't have any reference to it.

**Comment by arnaud-zg** [comment]
@cernicc https://github.com/maticzav/graphql-middleware/releases/tag/v6.0.1
