### ISSUE TITLE
Support for operations middleware

### ISSUE THREAD

**Issue by Sytten** [maticzav/graphql-middleware#334]
I was wondering if you think it would be possible to build middleware around operations, or that needs to be handled at the GraphQL server level. I am trying to build a plugin that would log the start and end of the operation specifically.

**Comment by maticzav** [comment]
Have you tried using Apollo server’s plugins? That’s what I usually use.

**Comment by Sytten** [comment]
I am moving away from it, But my goal is to build a distributable all in one plugin for fields and operations.

**Comment by maticzav** [comment]
We had a plan of implementing that, but never finsihed it. What’s you alternative to Apollo Server?

**Comment by Sytten** [comment]
Well I would like to support all servers if possible with the plugin, so say at least the following:
- https://github.com/contrawork/graphql-helix
- https://github.com/graphql/express-graphql
- https://github.com/mercurius-js/mercurius

**Comment by Sytten** [comment]
Ok so I dug a bit and I am not sure it is possible really, most server don't seem to allow the execute function to be changed. So you most go with their hook and that is dependant on the implementation. So unsure if it is really the job of graphql middleware to do that.

**Comment by maticzav** [comment]
@Sytten, I am closing this issue as I am not sure whether it's still relevant. At the top of my head, maybe Envelop could be a solution for this. In any case, feel free to reopen if this still seems relevant 

http://github.com/dotansimha/envelop

**Comment by Sytten** [comment]
Yeah envelop is the way to go!
